[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "oven_time"
version = "1.0.0"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]